POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmtrdSIsImlkIjoiNjZiMjFlMGVkYTQ0ZmJlZDgxMjdjNDgyIiwiaWF0IjoxNzIzMTAyMjc3LCJleHAiOjE3MjMxMDU4Nzd9.yT6DyRmi_4Cz24Eze6XQrFLFa9hkwcQmdOqB4xNp7mU

{
    "title": "Mehiläisten Maailma",
    "author": "Maija Muro",
    "url": "maijamuro/kirjat/mehilaistenmaailma.com",
    "likes": 0
}