POST http://localhost:3003/api/blogs/66cdc2758a7974d16ddd3c70/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmtrdSIsImlkIjoiNjZiMjFlMGVkYTQ0ZmJlZDgxMjdjNDgyIiwiaWF0IjoxNzIzMTA1OTU0LCJleHAiOjE3MjMxMDk1NTR9.W3wvBUZHYEnbuHwa8tP0Au-we_mQJB2SQ2TNvhWJc3I

{
    "comment": "oldie goodie"
}